baseURL: 'https://coreyborad.github.io/'
defaultContentLanguage: en
languageCode: en
title: '!@#$%'
theme: LoveIt
googleAnalytics: ''
author:
  name: "Corey"
params:
  version: 0.2.X
  defaultTheme: dark
  dateFormat: '2006-01-02'
  page:
    share:
      enable: false
    comment:
      disqus:
        enable: true
        shortname: "coreyborad"
  header:
    desktopMode: fixed
    mobileMode: auto
  footer:
    enable: true
  search:
    enable: true
    type: algolia
    contentLength: 4000
    placeholder: ''
    maxResultLength: 10
    snippetLength: 30
    highlightTag: em
    absoluteURL: false
    algolia:
      index: blogs
      appID: 4ZC5U6TJPT
      searchKey: c2df8b65ec5ae1ace2c6657143c2df89
      vars:
        - title
        - summary
        - date
        - publishdate
        - expirydate
        - permalink
      params:
        - categories
        - tags
        - posts
  home:
    rss: 10
    profile:
      enable: false
      gravatarEmail: ''
      avatarURL: /images/avatar.png
      title: ''
      subtitle: ''
      typeit: true
      social: true
      disclaimer: ''
    posts:
      enable: true
      paginate: 10
menu:
  main:
    - identifier: posts
      pre: ''
      post: ''
      name: Posts
      url: /posts/
      title: ''
      weight: 1
    - identifier: tags
      pre: ''
      post: ''
      name: Tags
      url: /tags/
      title: ''
      weight: 2
    - identifier: categories
      pre: ''
      post: ''
      name: Categories
      url: /categories/
      title: ''
      weight: 3
    - identifier: documentation
      pre: ''
      post: ''
      name: Docs
      url: /categories/documentation/
      title: ''
      weight: 4
markup:
  highlight:
    noClasses: false
outputs:
  home:
    - HTML
    - RSS
    - JSON
    - Algolia
mediaTypes:
  text/plain:
    suffixes:
      - md
outputFormats:
  MarkDown:
    mediaType: text/plain
    isPlainText: true
    isHTML: false
  Algolia:
    baseName: algolia
    isPlainText: true
    mediaType: application/json
    notAlternative: true
